services:
  redis:
    image: 'redis:alpine'
    container_name: 'score-films-redis'
    volumes:
      - score-films-redis:/data
    networks:
      - score-films

  mysql:
    image: 'mysql:8.0'
    container_name: 'score-films-mysql'
    working_dir: /application
    volumes:
      - '.:/application'
      - score-films-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=db_score-films
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - '33066:3306'
    networks:
      - score-films

  webserver:
    image: 'nginx:alpine'
    container_name: 'score-films-webserver'
    working_dir: /application
    volumes:
      - '.:/application'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8080:80'
    networks:
      - score-films
    depends_on:
      - php-fpm

  php-fpm:
    container_name: 'score-films-php-fpm'
    build:
      context: docker/php-fpm
      args:
        WWWGROUP: ${GID:-1000}
        WWWUSER: ${UID:-1000}
    working_dir: /application
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '.:/application'
      - './docker/php-fpm/php-ini-overrides-linux.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
    networks:
      - score-films
    depends_on:
      - mysql
      - redis

networks:
  score-films:
    driver: bridge

volumes:
  score-films-mysql:
    driver: local
  score-films-redis:
    driver: local
